
backend: vosk # One of: whisper, vosk

# Vosk specific config
vosk:
    # The path to the vosk model to use, either absolute or relative to current working directory
    # Download from: https://alphacephei.com/vosk/models
    model_path: models/vosk/vosk-model-en-us-0.22

# Whisper specific config
whisper:
    # The name of the whisper model, without the ggml- and .bin.
    # One of: tiny, tiny.en, base, base.en, small, small.en, medium, medium.en, large-v1, large,
    # Download from: https://huggingface.co/ggerganov/whisper.cpp/tree/main
    # Place the model in models/whispercpp/
    model_name: tiny.en
    # The base directory of the models, either absolute or related to current working directory.
    # The models should be under a directory called whispercpp under this directory.
    base_dir: models

    # The language of the audio. Set to `auto` for auto-detect
    language: auto
    # Set to true to translate the audio transcription to english
    translate: false
